name: Laravel CI

on:
  push:
    branches:
      - main
      - develop

  pull_request:
    branches:
      - main

jobs:
  tests:
    name: Testes Laravel
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Configurar PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          extensions: mbstring, pdo_sqlite, bcmath, intl
          coverage: none

      - name: Instalar dependências
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Preparar ambiente
        run: |
          cp .env.example .env
          php artisan key:generate

      - name: Preparar SQLite
        run: |
          touch database/database.sqlite

      - name: Configurar banco de testes
        run: |
          echo "DB_CONNECTION=sqlite" >> .env
          echo "DB_DATABASE=${{ github.workspace }}/database/database.sqlite" >> .env
          echo "CACHE_STORE=array" >> .env
          echo "SESSION_DRIVER=array" >> .env
          echo "QUEUE_CONNECTION=sync" >> .env

      - name: Executar migrations
        run: php artisan migrate --force

      - name: Executar testes
        run: php artisan test